<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.1 setup script
 * Date: Mon, 27 Dec 2021 07:50:09 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: osticket-mysql-db.mysql.database.azure.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'osticket-mysql-db.mysql.database.azure.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['FirstDayOfCalendar'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['GZipDump'] = false;
$cfg['BZipDump'] = false;
$cfg['blowfish_secret'] = '`R|v21!5b[H\\FG9DQ@=cq*O`g}%#,[Ge';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>